### PR TITLE
fix(fastboot): verify not fastboot prior accessing this.element

### PR DESCRIPTION
**Pull request by sarbbottam**

### CODE REVIEW

**Comment by nlfurniss** [comment]
Going to patch this change and test it. Will report back

**Comment by nlfurniss** [comment]
Still seeing the error :(

```
java.lang.Throwable: Error in Ember run loop: Error: Accessing `this.element` is not allowed in non-interactive environments (such as FastBoot).
    at Class.get (/Users/nfurniss/code/voyager-web_trunk/tmp/broccoli-711145WDZSzI5dLR8/out-9617-broccoli_merge_trees_merge_build_trees/extended/assets/vendor-static.js:53802:30)
    at InertRenderer.getElement (/Users/nfurniss/code/voyager-web_trunk/tmp/broccoli-711145WDZSzI5dLR8/out-9617-broccoli_merge_trees_merge_build_trees/extended/assets/vendor-static.js:33819:19)
    at Class.trigger (/Users/nfurniss/code/voyager-web_trunk/tmp/broccoli-711145WDZSzI5dLR8/out-9617-broccoli_merge_trees_merge_build_trees/extended/assets/vendor-static.js:54943:23)
    at Class.didReceiveAttrs (/Users/nfurniss/code/voyager-web_trunk/tmp/broccoli-711145WDZSzI5dLR8/out-9617-broccoli_merge_trees_merge_build_trees/extended/assets/vendor.js:171547:51)
```

**Comment by sarbbottam** [comment]
I did not merge this :(

**Comment by sarbbottam** [comment]
Creating another one.

**Pull request merged**
